### ISSUE TITLE
SRAM Bootloader Breaks SW1 and SW2 on Daisy Field

### ISSUE THREAD

**Issue by byronellis** [electro-smith/libDaisy#534] opened 2022-06-30 16:31 UTC
Hi, switching to the SRAM-based boot loader (BOOT_SRAM) appears to break SW_1 and SW_2 on the Daisy Field. Specifically it seems like RisingEdge() is always true. Not sure if this is intentional or if there is a workaround, but the same code will work fine if you load the same code without the custom daisy boot loader.

**Comment by stephenhensley** [comment] 2022-07-11 23:39
@byronellis thanks for the bug report, we'll look into this!

**Comment by byronellis** [comment] 2022-07-13 01:15
No problem! If you need a minimal reproduction I can make one but it's pretty much "switches don't seem to work" so it's almost trivial 🙂

**Comment by dromer** [comment] 2023-12-06 09:46
Ok can confirm that with this branch of libDaisy and the bootloader the switches work as expected.

Really hope this gets merged/released soon, but at least I know the cause of the issue and that it will get resolved at some point.

**Comment by dromer** [comment] 2023-12-22 20:06
I suppose this ticket can now be counted as resolved. Or should it need a release tag for libDaisy first?

**Comment by dromer** [comment] 2024-02-23 12:44
This works now on bootloader v6 and beyond :)

**Closed** 2024-02-23 15:42 UTC
Labels: bug
